'''
Even Fibonacci numbers
Submit

 Show HTML problem content 
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
num_l = []
num = 1
a = 0
while num < 4000000:
    num_l.append(num)
    num = num_l[a] + num_l[a-1]
    a = a + 1
ans = 0
for check in num_l:
    if check % 2 ==0:
        ans = ans + check
print (ans)
